### ISSUE TITLE
Open CV Manager

### ISSUE THREAD

**Issue by EbadSyed** [jingjieli/ORB_SLAM2_Android_as#1]
OpenCV manager is no more available on Android App Store, how do i progress ?

**Comment by jingjieli** [comment]
You can download OpenCV for Android from: https://sourceforge.net/projects/opencvlibrary/files/opencv-android/
OpenCV Manager is under under its apk folder.

**Comment by EbadSyed** [comment]
Thanks it worked. I guess in future I would try top build static library so it isnt require anymore
